apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.config.name }}
  labels:
    app: {{ .Values.app.name }}
data:
  {{- range .Values.app.config.data }}
  {{ .key }}: {{ .value }}
  {{- end}}