apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otus-app-rs-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
    spec:
      containers:
      - name: otus-app
        image: docker.io/recvezitor/otus-app:latest
        ports:
          - containerPort: 5000