apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-demo-monitor
  labels:
    app: metrics-demo-monitor
    
spec:
  endpoints:
    - port: metrics
      interval: 15s
      path: /actuator/prometheus     
  selector:
    matchLabels:
      app: metrics-demo
  
