logging:
  level:
    com.dmboro.order: ${LOG_LEVEL:DEBUG}

server:
  port: ${TARGET_PORT:5000}

spring:
  application.name: order
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}?currentSchema=${DB_SCHEMA:ordering}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        enable_lazy_load_no_trans: true
        default_schema: ${DB_SCHEMA:ordering}
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 10

    open-in-view: false
  flyway:
    enabled: true
    schemas: ${DB_SCHEMA:ordering}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

management:
  health:
    livenessstate.enabled: false
    readinessstate.enabled: false
  endpoint.health.probes.enabled: false
  endpoints.web:
    exposure.include: [ "metrics", "prometheus", "health", "beans", "mappings", "monitoring", "info", "env" ]
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms
    export.prometheus.enabled: true

services:
  account:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:5001}
  stock:
    url: ${STOCK_SERVICE_URL:http://localhost:5002}